# Use root/example as user/password credentials
version: '3.1'

services:
  # run this before running application to install the dependencies (will sync to host mounted volume):
  # docker-compose run boxbilling bash -c "composer install -d /app/src"
  # then run docker-compose up
  boxbilling:
    image: ysf/boxbilling
    build: .
    volumes:
      - './srv:/app'
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t /app/src

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
